name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm lint
      - run: COVERAGE=true pnpm test 'tests/**/*.test.ts' && pnpm nyc report
